### PR TITLE
Feature/keyboard map

### PR DESCRIPTION
**Pull request by HarithaRamesh**
Currently saving the mapping in a dictionary. (not connected to db yet) To save config details of users, we can save this dictionary obj in our db.

### CODE REVIEW

**Comment by rahij** [comment]
Haven't tstee it, but code looks fine. Can the huge switch case for keyboard input be automated or something?

**Comment by HarithaRamesh** [comment]
Well it's mapping the keycodes to their respective names. I don't think they have a method to get the names wrt keycodes unless we use a keyboard library (but the ones I've looked at are more for keyboard shortcuts/multiple presses). Perhaps, I could put all the possible names in an array matching the keycodes to their respective array position to make it cleaner.

**Comment by rahij** [comment]
Ah this is for displaying the names right? yeah maybe put it in a YAML file and parse it?

**Comment by HarithaRamesh** [comment]
Ooh Interesting. Never thought of that. Okay shall do that then.

**Comment by HarithaRamesh** [comment]
UI could be stylised better. But this is the gist of it.

**Pull request merged**
